name: Terraform CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: HashiTalks-India-2025/01-zero-shot
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform FMT (check)
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false
        env:
          TF_INPUT: "false"

      - name: Terraform Validate
        run: terraform validate -no-color


